CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS cln;
CREATE SCHEMA IF NOT EXISTS cur;
CREATE SCHEMA IF NOT EXISTS quarantine;
CREATE SCHEMA IF NOT EXISTS meta;

CREATE SCHEMA IF NOT EXISTS dbt_stg;
CREATE SCHEMA IF NOT EXISTS dbt_cur;
CREATE SCHEMA IF NOT EXISTS dbt;
