#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -v shrw_password="$POSTGRES_RW_PW" \
  -v shr_password="$POSTGRES_R_PW" \
  -v shcon_password="$POSTGRES_CONSUMER_PW" \
  -v pgdb="$POSTGRES_DB" <<'EOSQL'
CREATE ROLE shrw WITH LOGIN PASSWORD :'shrw_password';
CREATE ROLE shr WITH LOGIN PASSWORD :'shr_password';
CREATE ROLE shcon WITH LOGIN PASSWORD :'shcon_password';

GRANT CONNECT ON DATABASE :"pgdb" TO shrw, shr, shcon;

-- Pipeline schemas only (not public): shrw/shr have no privileges on public
GRANT USAGE ON SCHEMA raw, cln, cur, quarantine, meta TO shrw, shr;
GRANT CREATE ON SCHEMA raw, cln, cur, quarantine, meta TO shrw;

-- Consumer: read-only on gold (cur) schema
GRANT USAGE ON SCHEMA cur TO shcon;

-- shrw: full access in pipeline schemas
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw TO shrw;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cln TO shrw;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cur TO shrw;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA quarantine TO shrw;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA meta TO shrw;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA raw TO shrw;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cln TO shrw;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cur TO shrw;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA quarantine TO shrw;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA meta TO shrw;

-- shr: read pipeline layers (not public)
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO shr;
GRANT SELECT ON ALL TABLES IN SCHEMA cln TO shr;
GRANT SELECT ON ALL TABLES IN SCHEMA cur TO shr;
GRANT SELECT ON ALL TABLES IN SCHEMA quarantine TO shr;
GRANT SELECT ON ALL TABLES IN SCHEMA meta TO shr;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA raw TO shr;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cln TO shr;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cur TO shr;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA quarantine TO shr;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA meta TO shr;

-- shcon: read-only on cur (for now cur, later would make a cons layer if i want)
GRANT SELECT ON ALL TABLES IN SCHEMA cur TO shcon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cur TO shcon;

-- New objects created by shrw are readable to shr (or shcon if cur)
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA raw GRANT SELECT ON TABLES TO shr;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA raw GRANT SELECT ON SEQUENCES TO shr;

ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA cln GRANT SELECT ON TABLES TO shr;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA cln GRANT SELECT ON SEQUENCES TO shr;

ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA quarantine GRANT SELECT ON TABLES TO shr;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA quarantine GRANT SELECT ON SEQUENCES TO shr;

ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA cur GRANT SELECT ON TABLES TO shr;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA cur GRANT SELECT ON SEQUENCES TO shr;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA cur GRANT SELECT ON TABLES TO shcon;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA cur GRANT SELECT ON SEQUENCES TO shcon;

ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA meta GRANT SELECT ON TABLES TO shr;
ALTER DEFAULT PRIVILEGES FOR ROLE shrw IN SCHEMA meta GRANT SELECT ON SEQUENCES TO shr;
EOSQL
